# ===================================
#  List Behavior Config
# ===================================

title: valezdesign.recipes::lang.menu.posts
list: ~/plugins/valezdesign/recipes/models/posts/columns.yaml

modelClass: Valezdesign\Recipes\Models\Posts
recordUrl: valezdesign/recipes/posts/update/:id
noRecordsMessage: backend::lang.list.no_records

recordsPerPage: 15
showCheckboxes: true
showSetup: true

defaultSort:
    column: created_at
    direction: desc

toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt

filter: config_filter.yaml
